default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: roulettetest-dev
  pool: 5
  username: r1
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: roulettetest_test
  pool: 5
  username: r1
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: roulettetest-prod
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST