# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ab1ff898146c2bc1263a710a6297944fc90e2268ecec21064c73ef9a68b07501c08e7b322c7a96c24983f44083c84026ab13a186b31a8e7b28f1e414b9bfe2

test:
  secret_key_base: 283dbf0e43f361ac2cf51ad1e15b73d5fd9d8ba15cfe4efc39a9a74f266b8d60c1e63c81ab586c88f29e506e4a4a4153061b6d53b0ddfdeca530f06205c61fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
